version: '3.4'

services:
  db:
    image: rest-with-asp-net-udemy-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
    ports:
      - 3308:3306
    networks:
      - udemy-network

  rest-with-asp-net-udemy:
    image: rest-with-asp-net-udemy
    build:
      context: .
      dockerfile: RestWithASPNETUdemy/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    volumes:
      - ./UploadDir:/app/UploadDir
    depends_on:
      - db
    networks:
      - udemy-network
  
  rest-with-asp-net-udemy-front-end:
    image: rest-with-asp-net-udemy-front-end
    build:
      context: ..
      dockerfile: Client/Dockerfile
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 80:80
    volumes:
      - ../Client/src:/app/src
      - ../Client/public:/app/public
    depends_on:
      - db
    networks:
      - udemy-network

networks:
  udemy-network:
    driver: bridge
